service: anomaly-pipeline
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  environment:
    BUCKET_NAME: ${self:custom.bucketName}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:PutObjectAcl
          Resource: "arn:aws:s3:::${self:custom.bucketName}/*"

custom:
  bucketName: portfolio-pipeline-bucket-${sls:stage}-${opt:region, self:provider.region}

functions:
  anomalyDetector:
    handler: handler.lambda_handler
    events:
      # Run every 2 minutes automatically
      - schedule: rate(2 minutes)

resources:
  Resources:
    PipelineBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ["*"]
              AllowedMethods: [GET, HEAD]
              AllowedOrigins: ["*"]
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          IgnorePublicAcls: false
          BlockPublicPolicy: false
          RestrictPublicBuckets: false
